---
fixtures:
  repositories:
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    augeasproviders_sysctl:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_sysctl
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    gpasswd:
      branch: 5.X
      repo: https://github.com/simp/puppet-gpasswd
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    named:
      repo: https://github.com/simp/pupmod-simp-named
      branch: 5.X
    oddjob:
      repo: https://github.com/simp/pupmod-simp-oddjob
      branch: 5.X
    pam:
      repo: https://github.com/simp/pupmod-simp-pam
      branch: 5.X
    rsync:
      repo: https://github.com/simp/pupmod-simp-rsync
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    sudo:
      repo: https://github.com/simp/pupmod-simp-sudo
      branch: 5.X
    upstart:
      repo: https://github.com/simp/pupmod-simp-upstart
      branch: 5.X
  symlinks:
    simplib: "#{source_dir}"
