<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  win:
    roles:
      - windows
    platform: windows-server-amd64
    box: gusztavvargadr/windows-server
    box_version: 2102.0.2205
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    vagrant_cpus: 2
    user: vagrant
    communicator: winrm
    is_cygwin: false

CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
  ssh:
    keepalive: true
    keepalive_interval: 10
    host_key:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:host_key].join("\n#{' '*6}- ") %>
    kex:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:kex].join("\n#{' '*6}- ") %>
    encryption:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:encryption].join("\n#{' '*6}- ") %>
    hmac:
      - <%= Net::SSH::Transport::Algorithms::ALGORITHMS[:hmac].join("\n#{' '*6}- ") %>
