<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - default
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

  win:
    roles:
      - windows
    platform: windows-server-amd64
    box: devopsgroup-io/windows_server-2012r2-standard-amd64-nocm
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 2048
    vagrant_cpus: 2
    user: vagrant
    communicator: winrm
    is_cygwin: false
    ssh:
      host_key: '+ssh-dss'

CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
