HOSTS:
  el7:
    roles:
      - server
    masterless: true
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    # IPA needs more resources than those used in a typical module acceptance test
    vagrant_memsize: 2048
    vagrant_cpus: 2

  el7-client:
    roles:
      - client
    masterless: true
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant

  el6-client:
    roles:
      - client
      - no_fips
    masterless: true
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  vagrant_cpus: 1
